### ISSUE TITLE
The images in the dataset that have been released are very blurry. Do you know why?

### ISSUE THREAD

**Issue by bdfbdf321** [ai4ce/MARS#1]
![图片](https://github.com/ai4ce/MARS/assets/5656159/5331d578-3990-4f29-8a01-4f13e2f8057c)

**Comment by simbaforrest** [comment]
@bdfbdf321 Thank you for your interest. The current version that we got permission to release is of such quality. We are actively working on extending this to the next version which will have higher quality. Please stay tuned. We hope to release the next version soon.

**Comment by ZJWang9928** [comment]
Hi, thanks for your excellent job. When would the next version of your dataset be released?
