### ISSUE TITLE
multiagent dataset issue

### ISSUE THREAD

**Issue by chengm0-0** [ai4ce/MARS#2]
Hi, I have a small question. If I want to run the multiagent visualization code, do I need to download the entire multiagent dataset? Can't I download just one zip file for testing? Thanks

**Comment by chengm0-0** [comment]
In addition, I found that on the [website](https://ai4ce.github.io/MARS/multiagent/), the multiagent dataset and the multitraversal dataset point to the same Google Drive link. Is it because the multiagent dataset is not yet open?

**Comment by simbaforrest** [comment]
@zl3466 can you take a look into this? Thanks.

**Comment by zl3466** [comment]
> Hi, I have a small question. If I want to run the multiagent visualization code, do I need to download the entire multiagent dataset? Can't I download just one zip file for testing? Thanks

hi, thanks for asking. For multiagent, you do need to download the full set as the full set is one nuscenes object (with one folder of metadata tables). For multitraversal, you can download & play with one location at a time.

**Comment by zl3466** [comment]
> In addition, I found that on the [website](https://ai4ce.github.io/MARS/multiagent/), the multiagent dataset and the multitraversal dataset point to the same Google Drive link. Is it because the multiagent dataset is not yet open?

Thanks for letting me know! I have changed the download links to the correct ones on huggingface [here](https://huggingface.co/datasets/ai4ce/MARS/tree/main)
