### ISSUE TITLE
ground truth annotations

### ISSUE THREAD

**Issue by zongtianhu** [ai4ce/MARS#3]
Hello，does the publicly available Multiagent dataset have official ground truth annotations for the 3d detection task? If not, will it be annotated in the future?

**Comment by zl3466** [comment]
> Hello，does the publicly available Multiagent dataset have official ground truth annotations for the 3d detection task? If not, will it be annotated in the future?

Hi, we do not have annotations for the current version of the dataset, and yes we will provide annotations, e.g. bounding boxes with labels, in future versions.
